Add 'lite' stack for service-manual-publisher
Running 'rake' is successful. We can always improve support for this
app (to run web server stacks) when the need arises.

Note that service-manual-publisher uses a legacy 'structure.sql' to
manage the DB, so we need to use 'db:create' to populate the it.

Running 'db:migrate' won't work.

    StandardError: An error has occurred, this and all later migrations canceled:

    Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

      class CreateUsers < ActiveRecord::Migration[4.2]